from __future__ import annotations

from typing import Dict

PARAMETER_HELP: Dict[str, str] = {
    # ---------------- Main settings ----------------
    "use_svpwm": (
        "What it is:\n"
        "Enables the SVPWM average inverter model instead of applying dq voltage commands directly.\n\n"
        "Code variable:\n"
        "use_svpwm\n\n"
        "Small toy vehicle:\n"
        "Usually False for simple motor/control tests; True if studying inverter behavior.\n\n"
        "Usual EV vehicle:\n"
        "Usually True, because traction drives use PWM inverters.\n\n"
        "Notes:\n"
        "SVPWM affects PWM plots, duty cycles, and dead-time modeling."
    ),
    "include_deadtime": (
        "What it is:\n"
        "Includes inverter dead-time voltage error in the SVPWM model.\n\n"
        "Code variable:\n"
        "include_deadtime\n\n"
        "Small toy vehicle:\n"
        "False for ideal simulations; True for inverter-detail experiments.\n\n"
        "Usual EV vehicle:\n"
        "True if modeling real inverter switching effects.\n\n"
        "Notes:\n"
        "Only meaningful when use_svpwm = True."
    ),
    "machine_type": (
        "What it is:\n"
        "Selects motor type: surface PMSM or interior PMSM.\n\n"
        "Code variable:\n"
        "machine_type\n\n"
        "Small toy vehicle:\n"
        "Usually spmsm for small hobby/demo motors.\n\n"
        "Usual EV vehicle:\n"
        "Often ipmsm for traction motors because saliency enables MTPA and better field weakening.\n\n"
        "Notes:\n"
        "spmsm usually has Ld ≈ Lq. ipmsm usually has Ld ≠ Lq."
    ),
    "drive_mode": (
        "What it is:\n"
        "Chooses how the motor is driven: closed-loop FOC control or open-loop abc voltages.\n\n"
        "Code variable:\n"
        "drive_mode\n\n"
        "Small toy vehicle:\n"
        "closed_loop_foc for stable control; open_loop_abc only for demonstrations.\n\n"
        "Usual EV vehicle:\n"
        "closed_loop_foc.\n\n"
        "Notes:\n"
        "A PMSM is normally not stable under open-loop voltage drive unless synchronized carefully."
    ),
    "frame_mode": (
        "What it is:\n"
        "Selects how the dq axes rotate.\n\n"
        "Code variable:\n"
        "frame_mode\n\n"
        "rotor_foc:\n"
        "dq axes rotate with the rotor electrical angle. "
        "Use this for normal PMSM/IPMSM field-oriented control.\n\n"
        "stator:\n"
        "dq axes rotate with the stator supply frequency. "
        "Use mainly for open-loop or loss-of-sync demonstrations.\n\n"
        "Recommended:\n"
        "Use rotor_foc for controlled simulations.\n\n"
        "Notes:\n"
        "closed_loop_foc requires rotor_foc."
    ),
    "tfinal": (
        "What it is:\n"
        "Total simulation duration.\n\n"
        "Code variable:\n"
        "tfinal\n\n"
        "Small toy vehicle:\n"
        "0.1 to 5 s for quick transient tests; 10 to 30 s for thermal/load tests.\n\n"
        "Usual EV vehicle:\n"
        "5 to 60 s for drive-cycle segments; longer for thermal studies.\n\n"
        "Notes:\n"
        "Longer simulations take more time because the solver outputs many time samples."
        "Do NOT use inf or a very large number."
    ),
    "Imax": (
        "What it is:\n"
        "Maximum allowed stator current magnitude. It limits the current vector sqrt(id² + iq²).\n\n"
        "Code variable:\n"
        "Imax\n\n"
        "Small toy vehicle:\n"
        "1 to 30 A depending on motor/inverter size.\n\n"
        "Usual EV vehicle:\n"
        "100 to 800 A for traction systems; sometimes higher for short peak operation.\n\n"
        "Notes:\n"
        "This is a hard current ceiling for the controller and MTPA/FW logic.\n"
        "Imax limits how much current the controller/inverter is allowed to command."
    ),
    "poles": (
        "What it is:\n"
        "Total number of magnetic poles in the motor.\n\n"
        "Code variable:\n"
        "poles\n\n"
        "Small toy vehicle:\n"
        "4 to 14 poles is common.\n\n"
        "Usual EV vehicle:\n"
        "4 to 12 poles is common, but designs vary.\n\n"
        "Notes:\n"
        "Pole pairs = poles / 2. Electrical speed = pole pairs × mechanical speed."
    ),
    "f_pwm": (
        "What it is:\n"
        "PWM switching frequency of the inverter.\n\n"
        "Code variable:\n"
        "f_pwm\n\n"
        "Small toy vehicle:\n"
        "10 kHz to 30 kHz is common.\n\n"
        "Usual EV vehicle:\n"
        "5 kHz to 20 kHz is common.\n\n"
        "Notes:\n"
        "Higher PWM frequency improves current ripple but increases inverter switching losses."
    ),
    "use_mtpa": (
        "What it is:\n"
        "Enables Maximum Torque Per Ampere current reference generation for IPMSM.\n\n"
        "Code variable:\n"
        "use_mtpa\n\n"
        "Small toy vehicle:\n"
        "Usually False unless using an IPMSM model with saliency.\n\n"
        "Usual EV vehicle:\n"
        "Often True for IPMSM traction motors.\n\n"
        "Notes:\n"
        "Mostly useful for IPMSM. SPMSM usually gains little because Ld ≈ Lq."
    ),
    "use_field_weakening": (
        "What it is:\n"
        "Enables negative d-axis current above base speed to reduce effective flux and extend speed range.\n\n"
        "Code variable:\n"
        "use_field_weakening\n\n"
        "Small toy vehicle:\n"
        "Usually False for low-speed demos; True for high-speed tests.\n\n"
        "Usual EV vehicle:\n"
        "Usually True or available in the control strategy.\n\n"
        "Notes:\n"
        "Field weakening is important when back-EMF approaches the inverter voltage limit."
    ),

    # ---------------- Advanced electrical settings ----------------
    # "region": (
    #     "What it is:\n"
    #     "Simple supply-region preset selector used by the model.\n\n"
    #     "Code variable:\n"
    #     "region\n\n"
    #     "Small toy vehicle:\n"
    #     "Not very important; US or EU mainly affects default f and V_LL behavior.\n\n"
    #     "Usual EV vehicle:\n"
    #     "Usually not modeled by region directly; EVs use a DC battery/inverter bus.\n\n"
    #     "Notes:\n"
    #     "Your direct Vdc entry is usually more important than region."
    # ),
    "Vdc": (
        "What it is:\n"
        "DC bus voltage feeding the inverter.\n\n"
        "Code variable:\n"
        "Vdc\n\n"
        "Small toy vehicle:\n"
        "12 to 60 V for small battery vehicles; 24 or 48 V is common.\n\n"
        "Usual EV vehicle:\n"
        "300 to 900 V depending on vehicle architecture.\n\n"
        "Notes:\n"
        "In this model, approximate dq voltage limit is Vdc / sqrt(3)."
    ),
    "phi_f_ref": (
        "What it is:\n"
        "Permanent-magnet flux linkage at reference temperature.\n\n"
        "Code variable:\n"
        "phi_f_ref\n\n"
        "Small toy vehicle:\n"
        "About 0.002 to 0.05 Wb.\n\n"
        "Usual EV vehicle:\n"
        "About 0.03 to 0.3 Wb, sometimes higher depending on motor design.\n\n"
        "Notes:\n"
        "Higher flux usually gives higher torque per ampere but also higher back-EMF."
    ),
    "R_s_ref": (
        "What it is:\n"
        "Stator phase resistance at the reference temperature.\n"
        "This is usually the per-phase line-to-neutral resistance used by the dq model.\n\n"
        "Code variable:\n"
        "R_s_ref\n\n"
        "Small toy vehicle:\n"
        "About 0.05 to 5 Ω.\n\n"
        "Usual EV vehicle:\n"
        "About 0.005 to 0.2 Ω.\n\n"
        "Notes:\n"
        "Larger resistance causes more voltage drop and more copper loss."
    ),
    "J_motor": (
        "What it is:\n"
        "Rotor/motor inertia.\n\n"
        "Code variable:\n"
        "J_motor\n\n"
        "Small toy vehicle:\n"
        "About 1e-6 to 1e-3 kg·m².\n\n"
        "Usual EV vehicle:\n"
        "About 0.01 to 1 kg·m² depending on rotor size and drivetrain coupling.\n\n"
        "Notes:\n"
        "Larger inertia makes acceleration slower for the same torque."
    ),
    "wheel_radius": (
        "What it is:\n"
        "Vehicle wheel radius used to convert motor speed/load into vehicle motion.\n\n"
        "Code variable:\n"
        "wheel_radius\n\n"
        "Small toy vehicle:\n"
        "0.02 to 0.15 m.\n\n"
        "Usual EV vehicle:\n"
        "0.25 to 0.40 m.\n\n"
        "Notes:\n"
        "Larger wheels need more torque for the same tire force."
    ),
    "gear_ratio": (
        "What it is:\n"
        "Ratio of motor speed to wheel speed.\n"
        "gear_ratio = motor speed / wheel speed.\n\n"
        "Code variable:\n"
        "gear_ratio\n\n"
        "Small toy vehicle:\n"
        "About 5 to 30 for small geared motors.\n\n"
        "Usual EV vehicle:\n"
        "About 6 to 12 for single-speed traction drivetrains.\n\n"
        "Notes:\n"
        "A higher gear ratio means the motor spins faster than the wheel.\n"
        "This increases wheel torque but lowers vehicle speed for the same motor speed."
    ),
    "f": (
        "What it is:\n"
        "Electrical supply frequency used mainly for open-loop abc mode.\n\n"
        "Code variable:\n"
        "f\n\n"
        "Small toy vehicle:\n"
        "50 to 400 Hz depending on desired speed and pole count.\n\n"
        "Usual EV vehicle:\n"
        "Variable frequency from the inverter; can range from near 0 to several hundred Hz.\n\n"
        "Notes:\n"
        "In closed-loop FOC, rotor speed/reference is usually more important than this field.\n"
        "how fast the imposed three-phase stator voltage waveform rotates. \n"
        "The inverter changes electrical frequency according to desired motor speed."
    ),
    "V_LL": (
        "What it is:\n"
        "Line-to-line RMS voltage used for open-loop abc voltage generation.\n\n"
        "Code variable:\n"
        "V_LL\n\n"
        "Small toy vehicle:\n"
        "12 to 48 V RMS equivalent.\n\n"
        "Usual EV vehicle:\n"
        "Hundreds of volts equivalent, depending on inverter and bus voltage.\n\n"
        "Notes:\n"
        "Mostly relevant in open_loop_abc mode."
    ),
    "L_ls": (
        "What it is:\n"
        "Stator leakage inductance.\n"
        "It represents stator magnetic flux that does not fully link with the rotor "
        "and therefore does not directly produce useful torque.\n\n"

        "Code variable:\n"
        "L_ls\n\n"

        "Small toy vehicle:\n"
        "About 10 µH to 5 mH.\n\n"

        "Usual EV vehicle:\n"
        "About 50 µH to 2 mH, but traction motors vary widely.\n\n"

        "Notes:\n"
        "L_ls is added to both Ld and Lq.\n"
        "A larger L_ls slows current changes and increases the voltage needed "
        "to control current at high speed."
    ),
    "L_A": (
        "What it is:\n"
        "Saliency-related inductance term used to construct dq inductances.\n\n"
        "Code variable:\n"
        "L_A\n\n"
        "Small toy vehicle:\n"
        "0 for SPMSM; about 1e-6 to 1e-3 H for IPMSM-like tests.\n\n"
        "Usual EV vehicle:\n"
        "Usually identified from motor data/FEM; often tens to hundreds of µH scale.\n\n"
        "Notes:\n"
        "See helper below."
    ),
    "L_B": (
        "What it is:\n"
        "Saliency difference term that helps create Ld ≠ Lq.\n\n"
        "Code variable:\n"
        "L_B\n\n"
        "Small toy vehicle:\n"
        "0 for SPMSM; small positive value for IPMSM examples.\n\n"
        "Usual EV vehicle:\n"
        "Usually identified from motor data/FEM; often tens to hundreds of µH scale.\n\n"
        "Notes:\n"
        "Increasing L_B increases the difference between Lq and Ld in this parameterization.\n"
        "See helper below."
    ),
    "I_rated": (
        "What it is:\n"
        "Rated phase current used as the reference scale for saturation parameters.\n\n"
        "Code variable:\n"
        "I_rated\n\n"
        "Small toy vehicle:\n"
        "1 to 30 A.\n\n"
        "Usual EV vehicle:\n"
        "100 to 500 A continuous is common, with higher peak currents possible.\n\n"
        "Notes:\n"
        "This is not necessarily the same as Imax. (Usually around 0.4-0.7 of the Imax)\n"
        "I_rated is not the hard current clamp; Imax is."
    ),
    "P_rated": (
        "What it is:\n"
        "Rated mechanical motor power used by the supervisory power limit.\n\n"
        "Code variable:\n"
        "P_rated\n\n"
        "Small toy vehicle:\n"
        "10 to 1000 W. Use 0 to disable the power clamp.\n\n"
        "Usual EV vehicle:\n"
        "30 kW to 300 kW depending on vehicle.\n\n"
        "Notes:\n"
        "If unknown, set P_rated = 0.0 to avoid an artificial torque limit."
    ),
    "Ld_inf_factor": (
        "What it is:\n"
        "High-current saturated d-axis inductance as a fraction of low-current Ld0.\n\n"
        "Code variable:\n"
        "Ld_inf_factor\n\n"
        "Small toy vehicle:\n"
        "0.5 to 1.0 if saturation is mild or unknown.\n\n"
        "Usual EV vehicle:\n"
        "0.3 to 0.8 depending on magnetic saturation.\n\n"
        "Notes:\n"
        "Smaller value means stronger d-axis saturation."
    ),
    "Lq_inf_factor": (
        "What it is:\n"
        "High-current saturated q-axis inductance as a fraction of low-current Lq0.\n\n"
        "Code variable:\n"
        "Lq_inf_factor\n\n"
        "Small toy vehicle:\n"
        "0.5 to 1.0 if saturation is mild or unknown.\n\n"
        "Usual EV vehicle:\n"
        "0.4 to 0.9 depending on design.\n\n"
        "Notes:\n"
        "Smaller value means stronger q-axis saturation."
    ),
    "I_Ld_sat_factor": (
        "What it is:\n"
        "d-axis saturation current scale normalized by rated phase current.\n\n"
        "Code variable:\n"
        "I_Ld_sat_factor\n\n"
        "Small toy vehicle:\n"
        "0.5 to 2.0.\n\n"
        "Usual EV vehicle:\n"
        "0.5 to 1.5 × rated current is a reasonable modeling range.\n\n"
        "Notes:\n"
        "I_Ld_sat = I_Ld_sat_factor × I_rated. Smaller value means Ld drops earlier."
    ),
    "I_Lq_sat_factor": (
        "What it is:\n"
        "q-axis saturation current scale normalized by rated phase current.\n\n"
        "Code variable:\n"
        "I_Lq_sat_factor\n\n"
        "Small toy vehicle:\n"
        "0.5 to 2.5.\n\n"
        "Usual EV vehicle:\n"
        "0.5 to 2.0 × rated current is a reasonable modeling range.\n\n"
        "Notes:\n"
        "I_Lq_sat = I_Lq_sat_factor × I_rated. Smaller value means Lq drops earlier."
    ),

    # ---------------- Thermal settings ----------------
    "T_ref": (
        "What it is:\n"
        "Reference temperature for resistance and magnet flux values.\n\n"
        "Code variable:\n"
        "T_ref\n\n"
        "Small toy vehicle:\n"
        "Usually 20 or 25 °C.\n\n"
        "Usual EV vehicle:\n"
        "Usually 20 or 25 °C for datasheet/reference parameters.\n\n"
        "Notes:\n"
        "R_s_ref and phi_f_ref are interpreted at this temperature."
    ),
    "alpha_cu": (
        "What it is:\n"
        "Copper resistance temperature coefficient.\n\n"
        "Code variable:\n"
        "alpha_cu\n\n"
        "Typical value:\n"
        "About 0.0039 1/°C for copper.\n\n"
        "Notes:\n"
        "Used in the temperature-dependent R_s model."
        "Higher stator temperature increases stator resistance."
    ),
    "alpha_phi": (
        "What it is:\n"
        "Permanent-magnet flux temperature coefficient.\n\n"
        "Code variable:\n"
        "alpha_phi\n\n"
        "Typical value:\n"
        "About 0.0008 to 0.0012 1/°C for NdFeB magnets.\n\n"
        "Notes:\n"
        "Used in the temperature-dependent phi_f model."
        "Higher magnet temperature reduces PM flux in this model."
    ),
    "C_th_s": (
        "What it is:\n"
        "Stator thermal capacitance. Larger value means slower stator temperature rise.\n\n"
        "Code variable:\n"
        "C_th_s\n\n"
        "Small toy vehicle:\n"
        "10 to 500 J/K.\n\n"
        "Usual EV vehicle:\n"
        "1000 to 50000 J/K depending on motor size and cooling.\n\n"
        "Notes:\n"
        "Use approximate values unless you have thermal test data."
    ),
    "C_th_m": (
        "What it is:\n"
        "Magnet/rotor thermal capacitance. Larger value means slower magnet temperature rise.\n\n"
        "Code variable:\n"
        "C_th_m\n\n"
        "Small toy vehicle:\n"
        "10 to 500 J/K.\n\n"
        "Usual EV vehicle:\n"
        "1000 to 50000 J/K depending on rotor size.\n\n"
        "Notes:\n"
        "The magnet temperature affects PM flux."
    ),
    "R_th_sa": (
        "What it is:\n"
        "Thermal resistance from stator to ambient.\n\n"
        "Code variable:\n"
        "R_th_sa\n\n"
        "Small toy vehicle:\n"
        "0.5 to 20 K/W.\n\n"
        "Usual EV vehicle:\n"
        "0.01 to 1 K/W with good cooling.\n\n"
        "Notes:\n"
        "Lower value means better heat removal."
    ),
    "R_th_sm": (
        "What it is:\n"
        "Thermal resistance between stator and magnet/rotor.\n\n"
        "Code variable:\n"
        "R_th_sm\n\n"
        "Small toy vehicle:\n"
        "0.5 to 20 K/W.\n\n"
        "Usual EV vehicle:\n"
        "0.05 to 2 K/W depending on motor construction.\n\n"
        "Notes:\n"
        "Controls how quickly stator heat reaches the magnets."
    ),
    "R_th_ma": (
        "What it is:\n"
        "Thermal resistance from magnet/rotor to ambient.\n\n"
        "Code variable:\n"
        "R_th_ma\n\n"
        "Small toy vehicle:\n"
        "1 to 30 K/W.\n\n"
        "Usual EV vehicle:\n"
        "0.05 to 3 K/W depending on cooling path.\n\n"
        "Notes:\n"
        "Lower value means magnets cool more easily."
    ),
    "T_amb": (
        "What it is:\n"
        "Ambient air/cooling temperature around the motor.\n\n"
        "Code variable:\n"
        "T_amb\n\n"
        "Small toy vehicle:\n"
        "20 to 40 °C.\n\n"
        "Usual EV vehicle:\n"
        "-20 to 60 °C environment; coolant may be 20 to 80 °C.\n\n"
        "Notes:\n"
        "This is the thermal model reference environment."
    ),
    "T_warn_stator": (
        "What it is:\n"
        "Warning threshold for stator temperature.\n\n"
        "Code variable:\n"
        "T_warn_stator\n\n"
        "Small toy vehicle:\n"
        "80 to 120 °C.\n\n"
        "Usual EV vehicle:\n"
        "120 to 180 °C depending on insulation class.\n\n"
        # "Notes:\n"
        # "Warning threshold should be below fault threshold."
    ),
    "T_fault_stator": (
        "What it is:\n"
        "Fault/shutdown threshold for stator temperature.\n\n"
        "Code variable:\n"
        "T_fault_stator\n\n"
        "Small toy vehicle:\n"
        "100 to 160 °C.\n\n"
        "Usual EV vehicle:\n"
        "150 to 220 °C depending on insulation and protection strategy.\n\n"
        "Notes:\n"
        "Must be greater than T_warn_stator."
    ),
    "T_warn_magnet": (
        "What it is:\n"
        "Warning threshold for magnet temperature.\n\n"
        "Code variable:\n"
        "T_warn_magnet\n\n"
        "Small toy vehicle:\n"
        "70 to 110 °C.\n\n"
        "Usual EV vehicle:\n"
        "100 to 160 °C depending on magnet grade.\n\n"
        "Notes:\n"
        "Magnets can permanently weaken if overheated."
    ),
    "T_fault_magnet": (
        "What it is:\n"
        "Fault/shutdown threshold for magnet temperature.\n\n"
        "Code variable:\n"
        "T_fault_magnet\n\n"
        "Small toy vehicle:\n"
        "90 to 140 °C.\n\n"
        "Usual EV vehicle:\n"
        "140 to 200 °C depending on magnet grade.\n\n"
        "Notes:\n"
        "Must be greater than T_warn_magnet."
    ),
    "T_demag": (
        "What it is:\n"
        "Demagnetization-risk temperature threshold.\n\n"
        "Code variable:\n"
        "T_demag\n\n"
        "Small toy vehicle:\n"
        "80 to 140 °C depending on magnet quality.\n\n"
        "Usual EV vehicle:\n"
        "120 to 200 °C depending on magnet grade and design margin.\n\n"
        "Notes:\n"
        "Use datasheet magnet limits if available."
    ),
    "phi_f_min_factor": (
        "What it is:\n"
        "Lower limit for PM flux, written as a fraction of phi_f_ref.\n"
        "Example: 0.2 means phi_f cannot fall below 20% of phi_f_ref.\n\n"
        "Code variable:\n"
        "phi_f_min_factor\n\n"
        "Typical value:\n"
        "About 0.2 to 0.8 for protective numerical modeling.\n\n"
        "Notes:\n"
        "Used as a safety floor in the temperature-dependent phi_f model.\n"
        "It prevents flux from becoming zero, negative, or unphysical."
    ),

    # ---------------- Iron (core) loss settings ----------------
    "include_iron_loss": (
        "What it is:\n"
        "Enables a Steinmetz-style stator core (iron) loss model, added as an extra "
        "heat source at the stator thermal node.\n\n"
        "Code variable:\n"
        "include_iron_loss\n\n"
        "Based on:\n"
        "Mi, Slemon, Bonert, \"Modeling of Iron Losses of Permanent-Magnet Synchronous "
        "Motors\", IEEE Trans. Ind. Appl., 2003.\n\n"
        "Notes:\n"
        "When False (default), iron losses are ignored, matching the model's previous "
        "behavior (P_rotor stayed at a placeholder of 0.0)."
    ),
    "k_h_iron": (
        "What it is:\n"
        "Hysteresis loss coefficient in the Steinmetz equation "
        "p_iron = k_h*B^beta*omega_s + k_e*B^2*omega_s^2 [W/m³].\n\n"
        "Code variable:\n"
        "k_h_iron\n\n"
        "Typical value:\n"
        "About 40 to 55, from curve-fitting the lamination manufacturer's loss data.\n\n"
        "Notes:\n"
        "Only used when include_iron_loss = True."
    ),
    "k_e_iron": (
        "What it is:\n"
        "Eddy-current loss coefficient in the same Steinmetz equation.\n\n"
        "Code variable:\n"
        "k_e_iron\n\n"
        "Typical value:\n"
        "About 0.04 to 0.07.\n\n"
        "Notes:\n"
        "Only used when include_iron_loss = True."
    ),
    "beta_iron": (
        "What it is:\n"
        "Steinmetz exponent applied to the flux-density term.\n\n"
        "Code variable:\n"
        "beta_iron\n\n"
        "Typical value:\n"
        "About 1.8 to 2.2, close to 2.0 for most electrical steels.\n\n"
        "Notes:\n"
        "Only used when include_iron_loss = True."
    ),
    "core_volume_m3": (
        "What it is:\n"
        "Lumped stator core (teeth + yoke) volume used to convert the Steinmetz "
        "loss density [W/m³] into a total power [W].\n\n"
        "Code variable:\n"
        "core_volume_m3\n\n"
        "Small toy vehicle:\n"
        "About 1e-4 to 1e-3 m³ for small demo motors.\n\n"
        "Usual EV vehicle:\n"
        "About 1e-3 to 1e-2 m³ depending on motor size.\n\n"
        "Notes:\n"
        "This model has no explicit geometry (tooth width, yoke height, tooth "
        "count, etc.), so the article's per-tooth/per-yoke breakdown is lumped "
        "into this single effective volume. If include_iron_loss = True and this "
        "is left at 0, iron loss will always compute to 0 W."
    ),
    "B_iron_rated": (
        "What it is:\n"
        "Peak core flux density [T] assumed to occur at rated operation "
        "(id = 0, iq = I_rated). The instantaneous flux density is then scaled "
        "from that point as B_core = B_iron_rated * |lambda_dq| / lambda_rated, "
        "where lambda_rated = hypot(phi_f_ref, Lq0 * I_rated).\n\n"
        "Code variable:\n"
        "B_iron_rated\n\n"
        "Typical value:\n"
        "About 1.2 to 1.5 T for typical tooth/yoke saturation levels in "
        "electrical-steel laminations (see Table I of the reference article).\n\n"
        "Notes:\n"
        "This is a simplified stand-in for a real FEA/geometry-based flux-density "
        "waveform, needed because this model doesn't track tooth/yoke geometry."
    ),

    # ---------------- Vehicle/load settings ----------------
    "rho_air": (
        "What it is:\n"
        "Air density used for aerodynamic drag.\n\n"
        "Code variable:\n"
        "rho_air\n\n"
        "Typical value:\n"
        "Use 1.225 kg/m³ for sea-level standard air.\n\n"
        "Notes:\n"
        "Aero drag force is proportional to rho_air * Cd * A_front * v²."
    ),
    "drivetrain_eff": (
        "What it is:\n"
        "Mechanical efficiency from motor to wheel.\n\n"
        "Code variable:\n"
        "drivetrain_eff\n\n"
        "Small toy vehicle:\n"
        "0.7 to 0.95.\n\n"
        "Usual EV vehicle:\n"
        "0.9 to 0.98 for efficient EV drivetrains.\n\n"
        "Notes:\n"
        "1.0 means ideal drivetrain with no mechanical loss."
    ),
    "Cd": (
        "What it is:\n"
        "Aerodynamic drag coefficient.\n"
        "It describes how slippery or boxy the vehicle shape is in air.\n\n"
        "Code variable:\n"
        "Cd\n\n"
        "Small toy vehicle:\n"
        "About 0.5 to 1.5 for simple box-like shapes.\n\n"
        "Usual EV vehicle:\n"
        "About 0.20 to 0.35 for streamlined passenger EVs.\n\n"
        "How to imagine it:\n"
        "Low Cd = smooth shape that cuts through air easily.\n"
        "High Cd = blunt shape that pushes more air and needs more torque at speed.\n\n"
        "Notes:\n"
        "Set Cd = 0 to remove aerodynamic drag."
    ),
    "A_front": (
        "What it is:\n"
        "Vehicle frontal area.\n\n"
        "Code variable:\n"
        "A_front\n\n"
        "Small toy vehicle:\n"
        "0.005 to 0.1 m².\n\n"
        "Usual EV vehicle:\n"
        "1.8 to 2.8 m² for passenger vehicles.\n\n"
        "Notes:\n"
        "Set A_front = 0 to remove aerodynamic drag."
    ),
    "b_vehicle": (
        "What it is:\n"
        "Lumped speed-dependent loss coefficient.\n"
        "It adds a resisting force proportional to vehicle speed.\n\n"
        "Code variable:\n"
        "b_vehicle\n\n"
        "Small toy vehicle:\n"
        "About 0 to 2 N/(m/s).\n\n"
        "Usual EV vehicle:\n"
        "About 0 to 20 N/(m/s), depending on how much extra loss is included.\n\n"
        "How to imagine it:\n"
        "It is like a simple damping term for losses not modeled separately, "
        "such as bearings, drivetrain drag, and other speed-dependent friction.\n\n"
        "Notes:\n"
        "Set b_vehicle = 0 to remove this extra viscous loss."
    ),

    # ---------------- PWM/solver settings ----------------
    "deadtime": (
        "What it is:\n"
        "Delay time inserted between switching one transistor off and the complementary transistor on.\n\n"
        "Code variable:\n"
        "deadtime\n\n"
        "Small toy vehicle:\n"
        "0.2e-6 to 3e-6 s.\n\n"
        "Usual EV vehicle:\n"
        "0.5e-6 to 5e-6 s depending on inverter devices.\n\n"
        "Notes:\n"
        "Only meaningful when use_svpwm and include_deadtime are True."
    ),
    "plot_pwm_num_periods": (
        "What it is:\n"
        "Number of PWM periods displayed in the zoomed PWM plots.\n\n"
        "Code variable:\n"
        "plot_pwm_num_periods\n\n"
        "Small toy vehicle:\n"
        "20 to 200.\n\n"
        "Usual EV vehicle:\n"
        "20 to 200 for visualization.\n\n"
        "Notes:\n"
        "More periods show a longer window but may make switching details harder to see."
    ),
    "pwm_plot_samples": (
        "What it is:\n"
        "Number of samples used for the zoomed PWM plots.\n\n"
        "Code variable:\n"
        "pwm_plot_samples\n\n"
        "Small toy vehicle:\n"
        "5000 to 50000.\n\n"
        "Usual EV vehicle:\n"
        "5000 to 50000 for visualization.\n\n"
        "Notes:\n"
        "Higher value makes smoother PWM plots but uses more memory/time."
    ),
    "rtol": (
        "What it is:\n"
        "Relative error tolerance for the ODE solver.\n"
        "It controls allowed error compared with the size of each state value.\n\n"
        "Code variable:\n"
        "rtol\n\n"
        "Small toy vehicle:\n"
        "1e-5 to 1e-7.\n\n"
        "Usual EV vehicle:\n"
        "1e-5 to 1e-7 for simulation studies.\n\n"
        "Notes:\n"
        "Smaller value is more accurate but slower."
    ),
    "atol": (
        "What it is:\n"
        "Absolute error tolerance for the ODE solver.\n"
        "It controls the smallest error level the solver tries to resolve.\n\n"
        "Code variable:\n"
        "atol\n\n"
        "Small toy vehicle:\n"
        "1e-7 to 1e-9.\n\n"
        "Usual EV vehicle:\n"
        "1e-7 to 1e-9 for simulation studies.\n\n"
        "Notes:\n"
        "Smaller value is more accurate but slower."
    ),
    "solver_method": (
        "What it is:\n"
        "Numerical ODE solver method.\n\n"
        "Code variable:\n"
        "solver_method\n\n"
        "Small toy vehicle:\n"
        "Radau is good for stiff motor/control simulations.\n\n"
        "Usual EV vehicle:\n"
        "Radau is also reasonable for stiff PMSM/control simulations.\n\n"
        "Notes:\n"
        "Your GUI currently allows only Radau."
    ),
    "plot_pwm_zoom_start": (
        "What it is:\n"
        "Start time for the PWM zoom window.\n\n"
        "Code variable:\n"
        "plot_pwm_zoom_start\n\n"
        "Small toy vehicle:\n"
        "Pick a time after the transient you want to inspect.\n\n"
        "Usual EV vehicle:\n"
        "Pick a time near the operating condition of interest.\n\n"
        "Notes:\n"
        "The zoom window must fit inside tfinal."
    ),

    # ---------------- Schedule section ----------------
    "speed_schedule": (
        "What it is:\n"
        "Piecewise speed-reference schedule.\n\n"
        "Code variables:\n"
        "t_steps, omega_steps\n\n"
        "Small toy vehicle:\n"
        "0 to 5000 rpm is common depending on gearing and motor.\n\n"
        "Usual EV vehicle:\n"
        "Motor speeds from 0 to 20000 rpm are common depending on drivetrain.\n\n"
        "Notes:\n"
        "The editor shows speed in RPM, but the backend stores omega_steps in rad/s."
    ),
    "mass_schedule": (
        "What it is:\n"
        "Piecewise vehicle mass/load schedule.\n\n"
        "Code variables:\n"
        "mass_step_times, mass_step_values\n\n"
        "Small toy vehicle:\n"
        "0.5 to 20 kg.\n\n"
        "Usual EV vehicle:\n"
        "1000 to 3000 kg for passenger EV-scale vehicles.\n\n"
        "Notes:\n"
        "Mass contributes reflected inertia and road-load force."
    ),
    "slope_schedule": (
        "What it is:\n"
        "Piecewise road slope schedule in degrees.\n\n"
        "Code variables:\n"
        "slope_step_times, slope_step_values_deg\n\n"
        "Small toy vehicle:\n"
        "-10 to +10 deg for typical tests.\n\n"
        "Usual EV vehicle:\n"
        "-10 to +10 deg for normal roads; steeper grades are possible.\n\n"
        "Notes:\n"
        "Positive slope adds uphill load."
    ),
    "crr_schedule": (
        "What it is:\n"
        "Piecewise rolling-resistance coefficient schedule.\n\n"
        "Code variables:\n"
        "crr_step_times, crr_step_values\n\n"
        "Small toy vehicle:\n"
        "0.01 to 0.05 for wheels on smooth/rough surfaces.\n\n"
        "Usual EV vehicle:\n"
        "0.008 to 0.015 for passenger-car tires on asphalt.\n\n"
        "Notes:\n"
        "Higher Crr means more rolling load."
    ),
}